# 1.4.4 Smoothing Images

## Kernel Convolution

In [9]:
import cv2
import numpy as np
from matplotlib import pyplot as plt

In [10]:
l=1
kernel = np.array([[0,-1,0],[-1,4,-1],[0,-1,0]],np.float32)

In [11]:
kernel

array([[ 0., -1.,  0.],
       [-1.,  4., -1.],
       [ 0., -1.,  0.]], dtype=float32)

In [12]:
img = np.random.randint(10, size=(12,12))
#img = np.ones((10,10),np.float32)

In [13]:
img

array([[5, 4, 9, 1, 6, 9, 4, 9, 7, 5, 7, 6],
       [0, 5, 2, 5, 0, 0, 4, 5, 5, 0, 3, 8],
       [7, 8, 7, 9, 5, 3, 4, 5, 4, 9, 1, 4],
       [2, 2, 9, 8, 9, 8, 8, 4, 5, 9, 7, 3],
       [5, 8, 9, 9, 2, 5, 9, 4, 9, 0, 8, 4],
       [2, 1, 1, 3, 2, 5, 1, 5, 5, 7, 8, 4],
       [5, 5, 1, 7, 7, 1, 0, 1, 1, 4, 3, 7],
       [3, 9, 7, 3, 9, 3, 8, 6, 1, 1, 5, 5],
       [8, 1, 8, 1, 7, 7, 3, 2, 8, 1, 5, 2],
       [1, 7, 6, 9, 5, 6, 9, 8, 1, 7, 4, 8],
       [9, 9, 9, 6, 1, 3, 5, 6, 5, 6, 7, 1],
       [2, 7, 0, 1, 3, 2, 1, 0, 8, 1, 1, 0]])

In [20]:
h,w = img.shape

In [21]:
print(h,w)

512 512


In [22]:
#[*range(-2,3)]

In [ ]:
dst = np.zeros((h,w),np.int)

In [23]:
for i in range(l,h-l):
    for j in range(l,w-l):
        t=0
        for p in range(-l,l+1):
            for q in range(-l,l+1):
                t += kernel[p+l,q+l]*img[i+p,j+p]

In [24]:
img

array([[169, 169, 168, ..., 175, 162, 138],
       [169, 169, 168, ..., 175, 162, 138],
       [169, 169, 168, ..., 175, 162, 138],
       ...,
       [ 53,  53,  59, ..., 115, 112, 114],
       [ 53,  53,  64, ..., 117, 118, 122],
       [ 53,  53,  64, ..., 117, 118, 122]], dtype=uint8)

In [25]:
dst

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [31]:
img = cv2.imread('lena.png',0)

In [32]:
h,w = img.shape

In [33]:
dst = np.zeros((h-2*1,w-2*1),np.uint8)

In [36]:
for i in range(l,h-l):
    for j in range(l,w-l):
        t=0
        for p in range(-l,l+1):
            for q in range(-l,l+1):
                t += kernel[p+l,q+l]*img[i+p,j+p]
        dst[i-l,j-l]=t

In [37]:
cv2.imshow('img',img)
cv2.imshow('dst',dst)
cv2.waitKey(0)
cv2.destroyAllWindows()